/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    SingleColumnCenterRichTextBlock: SingleColumnCenterRichTextBlock;
    SpacerBlock: SpacerBlock;
    CardBulletPointSection: CardBulletPointSection;
    FeatureCardBlock: FeatureCardBlock;
  };
  collections: {
    users: User;
    media: Media;
    services: Service;
    projects: Project;
    'parent-services': ParentService;
    testimonials: Testimonial;
    processes: Process;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'parent-services': ParentServicesSelect<false> | ParentServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    processes: ProcessesSelect<false> | ProcessesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homePageGlobals: HomePageGlobal;
    aboutPageGlobals: AboutPageGlobal;
    ourWorkPageGlobals: OurWorkPageGlobal;
    contactPageGlobals: ContactPageGlobal;
    sentPageGlobals: SentPageGlobal;
    servicePageGlobals: ServicePageGlobal;
  };
  globalsSelect: {
    homePageGlobals: HomePageGlobalsSelect<false> | HomePageGlobalsSelect<true>;
    aboutPageGlobals: AboutPageGlobalsSelect<false> | AboutPageGlobalsSelect<true>;
    ourWorkPageGlobals: OurWorkPageGlobalsSelect<false> | OurWorkPageGlobalsSelect<true>;
    contactPageGlobals: ContactPageGlobalsSelect<false> | ContactPageGlobalsSelect<true>;
    sentPageGlobals: SentPageGlobalsSelect<false> | SentPageGlobalsSelect<true>;
    servicePageGlobals: ServicePageGlobalsSelect<false> | ServicePageGlobalsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SingleColumnCenterRichTextBlock".
 */
export interface SingleColumnCenterRichTextBlock {
  Copy: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'SingleColumnCenterRichTextBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'SpacerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBulletPointSection".
 */
export interface CardBulletPointSection {
  headerText: string;
  subheading: string;
  bulletPoints: {
    title: string;
    description: string;
    id?: string | null;
    blockName?: string | null;
    blockType: 'BulletPointBlock';
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'CardBulletPointSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureCardBlock".
 */
export interface FeatureCardBlock {
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  imageLeft: boolean;
  image: number | Media;
  button?:
    | {
        buttonText: string;
        buttonLink: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ButtonBlock';
      }[]
    | null;
  counter?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'FeatureCardBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  description: string;
  slug: string;
  icon: number | Media;
  /**
   * Lottie animation JSON
   */
  animatedIcon: string;
  hero: {
    title: string;
    subheading: string;
    buttonText: string;
    image: number | Media;
  };
  pageSections?:
    | (
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'SpacerBlock';
          }
        | {
            Copy: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'SingleColumnCenterRichTextBlock';
          }
        | {
            headerText: string;
            subheading: string;
            bulletPoints: {
              title: string;
              description: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'BulletPointBlock';
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'CardBulletPointSection';
          }
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            imageLeft: boolean;
            image: number | Media;
            button?:
              | {
                  buttonText: string;
                  buttonLink: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'ButtonBlock';
                }[]
              | null;
            counter?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'FeatureCardBlock';
          }
      )[]
    | null;
  parentService?: (number | null) | ParentService;
  seo: {
    title: string;
    description: string;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent-services".
 */
export interface ParentService {
  id: number;
  name: string;
  description: string;
  icon: number | Media;
  /**
   * Lottie animation JSON
   */
  animatedIcon: string;
  services?: (number | Service)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description: string;
  slug: string;
  cover: number | Media;
  forceSmall?: boolean | null;
  services?: (number | Service)[] | null;
  detailedText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  additionalImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  displayOrder?: number | null;
  seo: {
    title: string;
    description: string;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  quote: string;
  companyName: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processes".
 */
export interface Process {
  id: number;
  title: string;
  description: string;
  processNumber: string;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'parent-services';
        value: number | ParentService;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'processes';
        value: number | Process;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  icon?: T;
  animatedIcon?: T;
  hero?:
    | T
    | {
        title?: T;
        subheading?: T;
        buttonText?: T;
        image?: T;
      };
  pageSections?:
    | T
    | {
        SpacerBlock?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        SingleColumnCenterRichTextBlock?:
          | T
          | {
              Copy?: T;
              id?: T;
              blockName?: T;
            };
        CardBulletPointSection?:
          | T
          | {
              headerText?: T;
              subheading?: T;
              bulletPoints?:
                | T
                | {
                    BulletPointBlock?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        FeatureCardBlock?:
          | T
          | {
              text?: T;
              imageLeft?: T;
              image?: T;
              button?:
                | T
                | {
                    ButtonBlock?:
                      | T
                      | {
                          buttonText?: T;
                          buttonLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              counter?: T;
              id?: T;
              blockName?: T;
            };
      };
  parentService?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  cover?: T;
  forceSmall?: T;
  services?: T;
  detailedText?: T;
  additionalImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent-services_select".
 */
export interface ParentServicesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  icon?: T;
  animatedIcon?: T;
  services?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  quote?: T;
  companyName?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processes_select".
 */
export interface ProcessesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  processNumber?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePageGlobals".
 */
export interface HomePageGlobal {
  id: number;
  Home: {
    IntroText: string;
    projectsHeader: string;
    servicesHeader: string;
    projectsButtonText: string;
    Seo: {
      title: string;
      description: string;
      keywords?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPageGlobals".
 */
export interface AboutPageGlobal {
  id: number;
  About: {
    headerText: string;
    introductoryParagraph: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    processHeader: string;
    testimonialsHeader: string;
    Seo: {
      title: string;
      description: string;
      keywords?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ourWorkPageGlobals".
 */
export interface OurWorkPageGlobal {
  id: number;
  OurWork: {
    headerText: string;
    Seo: {
      title: string;
      description: string;
      keywords?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPageGlobals".
 */
export interface ContactPageGlobal {
  id: number;
  Contact: {
    headerText: string;
    contactExplanationText: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    submitButtonText: string;
    Seo: {
      title: string;
      description: string;
      keywords?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sentPageGlobals".
 */
export interface SentPageGlobal {
  id: number;
  ContactSent: {
    successHeader: string;
    successText: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    buttonText: string;
    /**
     * Lottie animation JSON
     */
    successIconAnimation: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicePageGlobals".
 */
export interface ServicePageGlobal {
  id: number;
  Services: {
    headerText: string;
    viewWorkHeader: string;
    viewWorkText: string;
    viewWorkButtonText: string;
    introductoryParagraph: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    Seo: {
      title: string;
      description: string;
      keywords?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePageGlobals_select".
 */
export interface HomePageGlobalsSelect<T extends boolean = true> {
  Home?:
    | T
    | {
        IntroText?: T;
        projectsHeader?: T;
        servicesHeader?: T;
        projectsButtonText?: T;
        Seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPageGlobals_select".
 */
export interface AboutPageGlobalsSelect<T extends boolean = true> {
  About?:
    | T
    | {
        headerText?: T;
        introductoryParagraph?: T;
        processHeader?: T;
        testimonialsHeader?: T;
        Seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ourWorkPageGlobals_select".
 */
export interface OurWorkPageGlobalsSelect<T extends boolean = true> {
  OurWork?:
    | T
    | {
        headerText?: T;
        Seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPageGlobals_select".
 */
export interface ContactPageGlobalsSelect<T extends boolean = true> {
  Contact?:
    | T
    | {
        headerText?: T;
        contactExplanationText?: T;
        submitButtonText?: T;
        Seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sentPageGlobals_select".
 */
export interface SentPageGlobalsSelect<T extends boolean = true> {
  ContactSent?:
    | T
    | {
        successHeader?: T;
        successText?: T;
        buttonText?: T;
        successIconAnimation?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicePageGlobals_select".
 */
export interface ServicePageGlobalsSelect<T extends boolean = true> {
  Services?:
    | T
    | {
        headerText?: T;
        viewWorkHeader?: T;
        viewWorkText?: T;
        viewWorkButtonText?: T;
        introductoryParagraph?: T;
        Seo?:
          | T
          | {
              title?: T;
              description?: T;
              keywords?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}